# Generated by Django 3.2.4 on 2021-08-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('LIQUIDS', 'Liquids'), ('NATURAL GOODS', 'Natural Goods'), ('CHEMICALS', 'Chemicals')], max_length=100),
        ),
    ]
